Repository GSG-G13/Team7-project, pull requests merged in 2023-04, with the labels that each got.

#6 add post ,signup schema
  package-lock.json
  package.json
  server/controller/posts.js
  server/utilis/validation/postSchema.js
  server/utilis/validation/signupSchema.js
Labels: done

#10 update the build.sql file
  server/database/config/build.sql
Labels: approved

#12 11 hashing function
  server/controller/hashing.js
  server/controller/hashverify.js
  server/controller/index.js
  server/controller/posts.js
  server/database/queries/addUser.js
Labels: approved

#15 add signup Relates #14
  public/script/signUp.js
  public/users/signUp.html
Labels: approved

#20 finishing user page rendering
  public/script/main.js
  public/script/signUp.js
  public/users/index.html
  server/controller/hashing.js
  server/controller/users.js
  server/database/queries/addUser.js
  server/database/queries/updateUserQuery.js
Labels: approved

#23 fixing realy realy small problem
  public/index.html
  public/script/main.js
  public/users/index.html
  server/database/config/connection.js
Labels: approved

#30 Relates #29
  public/users/login.html
  server/controller/error.js
  server/controller/index.js
  server/utilis/validation/loginSchema.js
Labels: waiting review

#28 13 compare passwords function
  index.js
  package-lock.json
  package.json
  public/script/login.js
  public/script/signUp.js
  public/users/login.html
  server/controller/comparePasswords.js
  server/controller/hashing.js
  server/controller/hashverify.js
  server/controller/index.js
  server/controller/users.js
  server/database/config/connection.js
  server/database/queries/addUser.js
  server/database/queries/getPasswordQuery.js
Labels: waiting review

#32 fix the login function and login.html file
  public/script/login.js
  public/users/login.html
  server/controller/comparePasswords.js
  server/controller/users.js
Labels: waiting review
